# Generated by Django 5.1.5 on 2026-08-23 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_location", models.CharField(max_length=200)),
                ("pickup_location", models.CharField(max_length=200)),
                ("dropoff_location", models.CharField(max_length=200)),
                ("current_cycle_used_hours", models.FloatField()),
                ("start_datetime", models.DateTimeField()),
                ("driver_name", models.CharField(blank=True, max_length=120)),
                ("carrier_name", models.CharField(blank=True, max_length=120)),
                ("truck_number", models.CharField(blank=True, max_length=60)),
                ("plan", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
